### ISSUE TITLE
Passing template path to config errors

### ISSUE THREAD

**Issue by cmalven** [jsBoot/gulp-docco#3]
Below is my docco task:

``` js
gulp.task('docco', function() {
  gulp.src(['index.js'])
    .pipe(tasks.docco({
      css: 'docco-custom.css',
      template: 'docco-custom.jst'
    }))
    .pipe(gulp.dest('./'));
});
```

Without the `template` property, everything works as expected. But with the template specified, the gulp task errors:

```
/Users/cmalven/Dropbox/Desktime/Desktime - Space Agreement/desktime-space-agreement/node_modules/gulp-docco/lib/backend.js:48
      var html = config.template({
                        ^
TypeError: Property 'template' of object #<Object> is not a function
    at process (/Users/cmalven/Dropbox/Desktime/Desktime - Space Agreement/desktime-space-agreement/node_modules/gulp-docco/lib/backend.js:48:25)
    at Transform.<anonymous> (/Users/cmalven/Dropbox/Desktime/Desktime - Space Agreement/desktime-space-agreement/node_modules/gulp-docco/index.js:70:14)
    at Transform.<anonymous> (/Users/cmalven/Dropbox/Desktime/Desktime - Space Agreement/desktime-space-agreement/node_modules/gulp-docco/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:130:12)
    at Transform.g (events.js:180:16)
    at Transform.EventEmitter.emit (events.js:92:17)
    at finishMaybe (/Users/cmalven/Dropbox/Desktime/Desktime - Space Agreement/desktime-space-agreement/node_modules/gulp-docco/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:363:12)
    at endWritable (/Users/cmalven/Dropbox/Desktime/Desktime - Space Agreement/desktime-space-agreement/node_modules/gulp-docco/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:370:3)
    at Transform.Writable.end (/Users/cmalven/Dropbox/Desktime/Desktime - Space Agreement/desktime-space-agreement/node_modules/gulp-docco/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:348:5)
    at Stream.onend (stream.js:79:10)
    at Stream.EventEmitter.emit (events.js:117:20)
```

Both css and jst files are in the same directly as the gulp file, and the custom css works perfectly. Any ideas?

**Comment by dmp42** [comment]
Indeed, it's a bug - and that code doesn't look too good :-)
Will patch.

**Comment by cmalven** [comment]
@dmp42 Glad to hear I'm not just going crazy! Thanks for the quick response. Loving this gulp plugin.

**Comment by dmp42** [comment]
That should be better now - pushed on npm as well.
All this is pretty new - be sure to report any shortcomings, I'll do my best to fix things swiftly.

**Comment by cmalven** [comment]
Wow, "swiftly" is right. Tested on my end and fix confirmed. Thanks a million.

**Comment by dmp42** [comment]
Welcome ;)

O.T.: just discovered your company - I like your website / what you do :+1:

**Comment by cmalven** [comment]
Thanks @dmp42! Really appreciate it.
