### ISSUE TITLE
Error: Cannot find module 'through2'

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [jsBoot/gulp-docco#7]
I am getting this error when running the gulp docco. I have lifted the version of through2 locally, which worked. 
Can you update the dependencies?

```
Error: Cannot find module 'through2'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at /Users/rob/Repos/thestack/node_modules/gulp-docco/index.js:4:18
  at Object.<anonymous> (/Users/rob/Repos/thestack/node_modules/gulp-docco/index.js:122:2)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/rob/Repos/thestack/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/rob/Repos/thestack/Gulpfile.coffee:25:9)
  at Object.<anonymous> (/Users/rob/Repos/thestack/Gulpfile.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/Users/rob/Repos/thestack/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/rob/Repos/thestack/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/rob/Repos/thestack/Gulpfile.js:4:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:159:12)
  at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.launch (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:152:5)
  at Object.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:67:5)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3

```

**Comment by eljefedelrodeodeljefe** [comment]
Stale.
